version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: spring_pg_db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5439:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
